-- USER_MANAGEMENT
CREATE SCHEMA USER_MANAGEMENT;

DROP TABLE IF EXISTS USER_MANAGEMENT.USER_PROFILE;
DROP TABLE IF EXISTS USER_MANAGEMENT.USER_FOLLOW;

CREATE TABLE USER_MANAGEMENT.USER_PROFILE (
    ID UUID NOT NULL,
    FIRST_NAME VARCHAR(512) NOT NULL,
    LAST_NAME VARCHAR(512) NOT NULL,
    EMAIL VARCHAR(512) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PROFILE_PICTURE_URL VARCHAR(2048),
    AUTHENTICATION_PROVIDER_ID VARCHAR(512) UNIQUE NOT NULL,
    FOLLOWS_COUNT BIGINT NOT NULL DEFAULT 0,
    FOLLOWED_BY_COUNT BIGINT NOT NULL DEFAULT 0
);

ALTER TABLE USER_MANAGEMENT.USER_PROFILE ADD CONSTRAINT PK_USER_PROFILE PRIMARY KEY(ID);

ALTER TABLE USER_MANAGEMENT.USER_PROFILE ADD CONSTRAINT FOLLOWS_COUNT_GREATER_EQUALS_ZERO CHECK(FOLLOWS_COUNT >= 0);
ALTER TABLE USER_MANAGEMENT.USER_PROFILE ADD CONSTRAINT FOLLOWED_BY_COUNT_GREATER_EQUALS_ZERO CHECK(FOLLOWED_BY_COUNT >= 0);

CREATE INDEX AUTHENTICATION_PROVIDER_ID_INDEX ON USER_MANAGEMENT.USER_PROFILE (AUTHENTICATION_PROVIDER_ID);

CREATE TABLE USER_MANAGEMENT.USER_FOLLOW (
    ID UUID NOT NULL,
    FOLLOWS_ID UUID NOT NULL,
    FOLLOWED_BY_ID UUID NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

ALTER TABLE USER_MANAGEMENT.USER_FOLLOW ADD CONSTRAINT PK_USER_FOLLOW PRIMARY KEY(ID);

ALTER TABLE USER_MANAGEMENT.USER_FOLLOW ADD CONSTRAINT FK_FOLLOWS_ID FOREIGN KEY(FOLLOWS_ID) REFERENCES USER_MANAGEMENT.USER_PROFILE(ID);
ALTER TABLE USER_MANAGEMENT.USER_FOLLOW ADD CONSTRAINT FK_FOLLOWED_BY_ID FOREIGN KEY(FOLLOWED_BY_ID) REFERENCES USER_MANAGEMENT.USER_PROFILE(ID);
ALTER TABLE USER_MANAGEMENT.USER_FOLLOW ADD CONSTRAINT FOLLOWS_ID_FOLLOWED_BY_ID_UNIQUE UNIQUE(FOLLOWS_ID, FOLLOWED_BY_ID);

CREATE INDEX FOLLOWS_ID_INDEX ON USER_MANAGEMENT.USER_FOLLOW (FOLLOWS_ID);
CREATE INDEX FOLLOWED_BY_ID_INDEX ON USER_MANAGEMENT.USER_FOLLOW (FOLLOWED_BY_ID);