-- CDN
CREATE SCHEMA CDN;

DROP TABLE IF EXISTS CDN.ASSET;

CREATE TABLE CDN.ASSET (
    ID UUID NOT NULL,
    FILE_NAME VARCHAR(512) NOT NULL,
    CONTENT_TYPE VARCHAR(256) NOT NULL,
    CONTENT_HASH VARCHAR(512) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    UPLOAD_TIME TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

ALTER TABLE CDN.ASSET ADD CONSTRAINT PK_ASSET PRIMARY KEY(ID);

CREATE INDEX FILE_NAME_INDEX ON CDN.ASSET (FILE_NAME);
CREATE INDEX CONTENT_HASH_INDEX ON CDN.ASSET (CONTENT_HASH);

-- USER_MANAGEMENT
CREATE SCHEMA USER_MANAGEMENT;

CREATE TABLE USER_MANAGEMENT.USER_PROFILE (
    ID UUID NOT NULL,
    FIRST_NAME VARCHAR(512) NOT NULL,
    LAST_NAME VARCHAR(512) NOT NULL,
    EMAIL VARCHAR(512) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PROFILE_PICTURE_URL VARCHAR(2048),
    AUTHENTICATION_PROVIDER_ID VARCHAR(512) NOT NULL
);

ALTER TABLE USER_MANAGEMENT.USER_PROFILE ADD CONSTRAINT PK_USER_PROFILE PRIMARY KEY(ID);

CREATE INDEX AUTHENTICATION_PROVIDER_ID_INDEX ON USER_MANAGEMENT.USER_PROFILE (AUTHENTICATION_PROVIDER_ID);