-- CDN
CREATE SCHEMA CDN;

DROP TABLE IF EXISTS CDN.ASSET;

CREATE TABLE CDN.ASSET
(
    ID           UUID                        NOT NULL,
    FILE_NAME    VARCHAR(512)                NOT NULL,
    CONTENT_TYPE VARCHAR(256)                NOT NULL,
    CONTENT_HASH VARCHAR(512)                NOT NULL,
    FILE_SIZE    BIGINT                      NOT NULL,
    UPLOAD_TIME  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

ALTER TABLE CDN.ASSET
    ADD CONSTRAINT PK_ASSET PRIMARY KEY (ID);

CREATE INDEX FILE_NAME_INDEX ON CDN.ASSET (FILE_NAME);
CREATE INDEX CONTENT_HASH_INDEX ON CDN.ASSET (CONTENT_HASH);

-- USER_MANAGEMENT
CREATE SCHEMA USER_MANAGEMENT;

DROP TABLE IF EXISTS USER_MANAGEMENT.USER_PROFILE;
DROP TABLE IF EXISTS USER_MANAGEMENT.USER_FOLLOW;

CREATE TABLE USER_MANAGEMENT.USER_PROFILE
(
    ID                         UUID                        NOT NULL,
    FIRST_NAME                 VARCHAR(512)                NOT NULL,
    LAST_NAME                  VARCHAR(512)                NOT NULL,
    EMAIL                      VARCHAR(512) UNIQUE         NOT NULL,
    CREATED_AT                 TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    UPDATED_AT                 TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PROFILE_PICTURE_URL        VARCHAR(2048),
    AUTHENTICATION_PROVIDER_ID VARCHAR(512) UNIQUE         NOT NULL,
    FOLLOWS_COUNT              BIGINT                      NOT NULL DEFAULT 0,
    FOLLOWED_COUNT             BIGINT                      NOT NULL DEFAULT 0
);

ALTER TABLE USER_MANAGEMENT.USER_PROFILE
    ADD CONSTRAINT PK_USER_PROFILE PRIMARY KEY (ID);

ALTER TABLE USER_MANAGEMENT.USER_PROFILE
    ADD CONSTRAINT FOLLOWS_COUNT_GREATER_EQUALS_ZERO CHECK (FOLLOWS_COUNT >= 0);
ALTER TABLE USER_MANAGEMENT.USER_PROFILE
    ADD CONSTRAINT FOLLOWED_COUNT_GREATER_EQUALS_ZERO CHECK (FOLLOWED_COUNT >= 0);

CREATE INDEX AUTHENTICATION_PROVIDER_ID_INDEX ON USER_MANAGEMENT.USER_PROFILE (AUTHENTICATION_PROVIDER_ID);

CREATE TABLE USER_MANAGEMENT.USER_FOLLOW
(
    ID          UUID                        NOT NULL,
    FOLLOWS_ID  UUID                        NOT NULL,
    FOLLOWED_ID UUID                        NOT NULL,
    CREATED_AT  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

ALTER TABLE USER_MANAGEMENT.USER_FOLLOW
    ADD CONSTRAINT PK_USER_FOLLOW PRIMARY KEY (ID);

ALTER TABLE USER_MANAGEMENT.USER_FOLLOW
    ADD CONSTRAINT FK_FOLLOWS_ID FOREIGN KEY (FOLLOWS_ID) REFERENCES USER_MANAGEMENT.USER_PROFILE (ID);
ALTER TABLE USER_MANAGEMENT.USER_FOLLOW
    ADD CONSTRAINT FK_FOLLOWED_ID FOREIGN KEY (FOLLOWED_ID) REFERENCES USER_MANAGEMENT.USER_PROFILE (ID);
ALTER TABLE USER_MANAGEMENT.USER_FOLLOW
    ADD CONSTRAINT FOLLOWS_ID_FOLLOWED_ID_UNIQUE UNIQUE (FOLLOWS_ID, FOLLOWED_ID);

CREATE INDEX FOLLOWS_ID_INDEX ON USER_MANAGEMENT.USER_FOLLOW (FOLLOWS_ID);
CREATE INDEX FOLLOWED_ID_INDEX ON USER_MANAGEMENT.USER_FOLLOW (FOLLOWED_ID);

-- Posts
CREATE SCHEMA POST_MANAGEMENT;

DROP TABLE IF EXISTS POST_MANAGEMENT.POST;
DROP TABLE IF EXISTS POST_MANAGEMENT.LIKE;
DROP TABLE IF EXISTS POST_MANAGEMENT.COMMENT;

CREATE TABLE POST_MANAGEMENT.POST
(
    ID             UUID,
    IMAGE_URL      VARCHAR(2048)            NOT NULL,
    OWNER_ID       UUID                     NOT NULL,
    LATITUDE       REAL,
    LONGITUDE      REAL,
    PLACE_NAME     VARCHAR(255),
    PLACE_ID       VARCHAR(255),
    LIKES_COUNT    BIGINT                   NOT NULL DEFAULT 0,
    COMMENTS_COUNT BIGINT                   NOT NULL DEFAULT 0,
    CREATED_AT     TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE POST_MANAGEMENT.POST
    ADD CONSTRAINT PK_POST PRIMARY KEY (ID);

CREATE INDEX OWNER_ID_INDEX ON POST_MANAGEMENT.POST (OWNER_ID);

CREATE TABLE POST_MANAGEMENT.LIKE
(
    ID         UUID PRIMARY KEY,
    POST_ID    UUID                     NOT NULL,
    USER_ID    UUID                     NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE POST_MANAGEMENT.LIKE
    ADD CONSTRAINT PK_LIKE PRIMARY KEY (ID);

ALTER TABLE POST_MANAGEMENT.LIKE
    ADD CONSTRAINT FK_POST_ID FOREIGN KEY (POST_ID) REFERENCES POST_MANAGEMENT.POST (ID) ON DELETE CASCADE;
ALTER TABLE USER_MANAGEMENT.LIKE
    ADD CONSTRAINT POST_ID_USER_ID_UNIQUE UNIQUE (POST_ID, USER_ID);

CREATE INDEX POST_ID_INDEX ON POST_MANAGEMENT.LIKE (POST_ID);
CREATE INDEX USER_ID_INDEX ON POST_MANAGEMENT.LIKE (USER_ID);

CREATE TABLE POST_MANAGEMENT.COMMENT
(
    ID         UUID PRIMARY KEY,
    POST_ID    UUID                     NOT NULL,
    USER_ID    UUID                     NOT NULL,
    CONTENT    TEXT                     NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE POST_MANAGEMENT.COMMENT
    ADD CONSTRAINT PK_COMMENT PRIMARY KEY (ID);

ALTER TABLE POST_MANAGEMENT.COMMENT
    ADD CONSTRAINT FK_COMMENT_POST_ID FOREIGN KEY (POST_ID) REFERENCES POST_MANAGEMENT.POST (ID) ON DELETE CASCADE;

CREATE INDEX POST_ID_INDEX ON POST_MANAGEMENT.COMMENT (POST_ID);
CREATE INDEX USER_ID_INDEX ON POST_MANAGEMENT.COMMENT (USER_ID);