-- Posts
CREATE SCHEMA POST_MANAGEMENT;

DROP TABLE IF EXISTS POST_MANAGEMENT.POST;
DROP TABLE IF EXISTS POST_MANAGEMENT.LIKE;
DROP TABLE IF EXISTS POST_MANAGEMENT.COMMENT;

CREATE TABLE POST_MANAGEMENT.POST (
      ID UUID,
      IMAGE_URL VARCHAR(2048) NOT NULL,
      OWNER_ID UUID NOT NULL,
      LATITUDE REAL,
      LONGITUDE REAL,
      PLACE_NAME VARCHAR(255),
      PLACE_ID VARCHAR(255),
      LIKES_COUNT BIGINT NOT NULL DEFAULT 0,
      COMMENTS_COUNT BIGINT NOT NULL DEFAULT 0,
      CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
      UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE POST_MANAGEMENT.POST ADD CONSTRAINT PK_POST PRIMARY KEY(ID);

CREATE INDEX OWNER_ID_INDEX ON POST_MANAGEMENT.POST(OWNER_ID);

CREATE TABLE POST_MANAGEMENT.LIKE (
      ID UUID PRIMARY KEY,
      POST_ID UUID NOT NULL,
      USER_ID UUID NOT NULL,
      CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE POST_MANAGEMENT.LIKE ADD CONSTRAINT PK_LIKE PRIMARY KEY(ID);

ALTER TABLE POST_MANAGEMENT.LIKE ADD CONSTRAINT FK_POST_ID FOREIGN KEY(POST_ID) REFERENCES POST_MANAGEMENT.POST(ID) ON DELETE CASCADE;
ALTER TABLE USER_MANAGEMENT.LIKE ADD CONSTRAINT POST_ID_USER_ID_UNIQUE UNIQUE(POST_ID, USER_ID);

CREATE INDEX POST_ID_INDEX ON POST_MANAGEMENT.LIKE(POST_ID);
CREATE INDEX USER_ID_INDEX ON POST_MANAGEMENT.LIKE(USER_ID);

CREATE TABLE POST_MANAGEMENT.COMMENT (
     ID UUID PRIMARY KEY,
     POST_ID UUID NOT NULL,
     USER_ID UUID NOT NULL,
     CONTENT TEXT NOT NULL,
     CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE POST_MANAGEMENT.COMMENT ADD CONSTRAINT PK_COMMENT PRIMARY KEY(ID);

ALTER TABLE POST_MANAGEMENT.COMMENT ADD CONSTRAINT FK_COMMENT_POST_ID FOREIGN KEY(POST_ID) REFERENCES POST_MANAGEMENT.POST(ID) ON DELETE CASCADE;

CREATE INDEX POST_ID_INDEX ON POST_MANAGEMENT.COMMENT(POST_ID);
CREATE INDEX USER_ID_INDEX ON POST_MANAGEMENT.COMMENT(USER_ID);