/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gr.evansp.momento.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class UserFollowAvro extends org.apache.avro.specific.SpecificRecordBase
    implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3235409966733079380L;

  public static final org.apache.avro.Schema SCHEMA$ =
      new org.apache.avro.Schema.Parser()
          .parse(
              "{\"type\":\"record\",\"name\":\"UserFollowAvro\",\"namespace\":\"gr.evansp.momento.avro\",\"fields\":[{\"name\":\"follows\",\"type\":\"string\"},{\"name\":\"followed\",\"type\":\"string\"},{\"name\":\"date\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static final SpecificData MODEL$ = new SpecificData();

  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.DateConversion());
  }

  private static final BinaryMessageEncoder<UserFollowAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserFollowAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserFollowAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserFollowAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserFollowAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserFollowAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserFollowAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserFollowAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserFollowAvro fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence follows;
  private java.lang.CharSequence followed;
  private java.time.LocalDate date;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserFollowAvro() {}

  /**
   * All-args constructor.
   * @param follows The new value for follows
   * @param followed The new value for followed
   * @param date The new value for date
   */
  public UserFollowAvro(
      java.lang.CharSequence follows, java.lang.CharSequence followed, java.time.LocalDate date) {
    this.follows = follows;
    this.followed = followed;
    this.date = date;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() {
    return MODEL$;
  }

  @Override
  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return follows;
      case 1:
        return followed;
      case 2:
        return date;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
        null, null, new org.apache.avro.data.TimeConversions.DateConversion(), null
      };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value = "unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        follows = (java.lang.CharSequence) value$;
        break;
      case 1:
        followed = (java.lang.CharSequence) value$;
        break;
      case 2:
        date = (java.time.LocalDate) value$;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'follows' field.
   * @return The value of the 'follows' field.
   */
  public java.lang.CharSequence getFollows() {
    return follows;
  }

  /**
   * Sets the value of the 'follows' field.
   * @param value the value to set.
   */
  public void setFollows(java.lang.CharSequence value) {
    this.follows = value;
  }

  /**
   * Gets the value of the 'followed' field.
   * @return The value of the 'followed' field.
   */
  public java.lang.CharSequence getFollowed() {
    return followed;
  }

  /**
   * Sets the value of the 'followed' field.
   * @param value the value to set.
   */
  public void setFollowed(java.lang.CharSequence value) {
    this.followed = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.time.LocalDate getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.time.LocalDate value) {
    this.date = value;
  }

  /**
   * Creates a new UserFollowAvro RecordBuilder.
   * @return A new UserFollowAvro RecordBuilder
   */
  public static gr.evansp.momento.avro.UserFollowAvro.Builder newBuilder() {
    return new gr.evansp.momento.avro.UserFollowAvro.Builder();
  }

  /**
   * Creates a new UserFollowAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserFollowAvro RecordBuilder
   */
  public static gr.evansp.momento.avro.UserFollowAvro.Builder newBuilder(
      gr.evansp.momento.avro.UserFollowAvro.Builder other) {
    if (other == null) {
      return new gr.evansp.momento.avro.UserFollowAvro.Builder();
    } else {
      return new gr.evansp.momento.avro.UserFollowAvro.Builder(other);
    }
  }

  /**
   * Creates a new UserFollowAvro RecordBuilder by copying an existing UserFollowAvro instance.
   * @param other The existing instance to copy.
   * @return A new UserFollowAvro RecordBuilder
   */
  public static gr.evansp.momento.avro.UserFollowAvro.Builder newBuilder(
      gr.evansp.momento.avro.UserFollowAvro other) {
    if (other == null) {
      return new gr.evansp.momento.avro.UserFollowAvro.Builder();
    } else {
      return new gr.evansp.momento.avro.UserFollowAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserFollowAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder
      extends org.apache.avro.specific.SpecificRecordBuilderBase<UserFollowAvro>
      implements org.apache.avro.data.RecordBuilder<UserFollowAvro> {

    private java.lang.CharSequence follows;
    private java.lang.CharSequence followed;
    private java.time.LocalDate date;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(gr.evansp.momento.avro.UserFollowAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.follows)) {
        this.follows = data().deepCopy(fields()[0].schema(), other.follows);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.followed)) {
        this.followed = data().deepCopy(fields()[1].schema(), other.followed);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.date)) {
        this.date = data().deepCopy(fields()[2].schema(), other.date);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing UserFollowAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(gr.evansp.momento.avro.UserFollowAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.follows)) {
        this.follows = data().deepCopy(fields()[0].schema(), other.follows);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.followed)) {
        this.followed = data().deepCopy(fields()[1].schema(), other.followed);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.date)) {
        this.date = data().deepCopy(fields()[2].schema(), other.date);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Gets the value of the 'follows' field.
     * @return The value.
     */
    public java.lang.CharSequence getFollows() {
      return follows;
    }

    /**
     * Sets the value of the 'follows' field.
     * @param value The value of 'follows'.
     * @return This builder.
     */
    public gr.evansp.momento.avro.UserFollowAvro.Builder setFollows(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.follows = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'follows' field has been set.
     * @return True if the 'follows' field has been set, false otherwise.
     */
    public boolean hasFollows() {
      return fieldSetFlags()[0];
    }

    /**
     * Clears the value of the 'follows' field.
     * @return This builder.
     */
    public gr.evansp.momento.avro.UserFollowAvro.Builder clearFollows() {
      follows = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'followed' field.
     * @return The value.
     */
    public java.lang.CharSequence getFollowed() {
      return followed;
    }

    /**
     * Sets the value of the 'followed' field.
     * @param value The value of 'followed'.
     * @return This builder.
     */
    public gr.evansp.momento.avro.UserFollowAvro.Builder setFollowed(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.followed = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'followed' field has been set.
     * @return True if the 'followed' field has been set, false otherwise.
     */
    public boolean hasFollowed() {
      return fieldSetFlags()[1];
    }

    /**
     * Clears the value of the 'followed' field.
     * @return This builder.
     */
    public gr.evansp.momento.avro.UserFollowAvro.Builder clearFollowed() {
      followed = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
     * Gets the value of the 'date' field.
     * @return The value.
     */
    public java.time.LocalDate getDate() {
      return date;
    }

    /**
     * Sets the value of the 'date' field.
     * @param value The value of 'date'.
     * @return This builder.
     */
    public gr.evansp.momento.avro.UserFollowAvro.Builder setDate(java.time.LocalDate value) {
      validate(fields()[2], value);
      this.date = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
     * Checks whether the 'date' field has been set.
     * @return True if the 'date' field has been set, false otherwise.
     */
    public boolean hasDate() {
      return fieldSetFlags()[2];
    }

    /**
     * Clears the value of the 'date' field.
     * @return This builder.
     */
    public gr.evansp.momento.avro.UserFollowAvro.Builder clearDate() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserFollowAvro build() {
      try {
        UserFollowAvro record = new UserFollowAvro();
        record.follows =
            fieldSetFlags()[0] ? this.follows : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.followed =
            fieldSetFlags()[1] ? this.followed : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.date =
            fieldSetFlags()[2] ? this.date : (java.time.LocalDate) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserFollowAvro> WRITER$ =
      (org.apache.avro.io.DatumWriter<UserFollowAvro>) MODEL$.createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserFollowAvro> READER$ =
      (org.apache.avro.io.DatumReader<UserFollowAvro>) MODEL$.createDatumReader(SCHEMA$);

  @Override
  public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }
}
